name: bilioteca_virtual
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.2"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.1
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_picker: ^8.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  firebase_ui_auth: ^1.15.0
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cached_pdfview: ^0.4.2
  flutter_gutter: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0

  loader_overlay: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^26.1.35
  uuid: ^4.4.0
  verify_payment:
    git: https://github.com/paulinofonsecas/veryfi_payment.git

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
