name: bilioteca_virtual
description: A Very Good Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.2"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.2.1
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  firebase_ui_auth: ^1.13.1
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_cached_pdfview: ^0.4.2
  flutter_gutter: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^14.2.8
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0

  loader_overlay: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  searchable_listview: ^2.14.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdf: ^26.2.8
  uuid: ^4.4.0
  verify_payment:
    git: https://github.com/paulinofonsecas/veryfi_payment.git
  device_preview: ^1.0.0
  dropdown_search: ^5.0.6
  flutter_modular: ^6.3.4
  google_mobile_ads: ^5.1.0
  lottie: ^3.1.2
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
  generate: true
